# =========================
# DATASOURCE POSTGRES
# =========================
spring.datasource.url=jdbc:postgresql://dietiestate25.cu1qeck227j7.us-east-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=gestore
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080


# =====================
# MAIL CON SPRING
# =====================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gedico3@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# =====================
# GOOGLE OAUTH2 CONFIG
# =====================
spring.security.oauth2.client.registration.google.client-id=1017609786940-8tqqgam44sfjkugmgj1mqa78iprvv0ei.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub


# =====================
# GITHUB OAUTH2 CONFIG
# =====================
spring.security.oauth2.client.registration.github.client-id=Ov23limLs6dTfYSoQmh8
spring.security.oauth2.client.registration.github.client-secret=9eaac68400dcff31d69fa3047a79187309753bf5
spring.security.oauth2.client.registration.github.scope=user:email
spring.security.oauth2.client.registration.github.redirect-uri=http://localhost:8080/login/oauth2/code/github
spring.security.oauth2.client.registration.github.client-name=GitHub
spring.security.oauth2.client.registration.github.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.github.client-authentication-method=client_secret_basic

spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user
spring.security.oauth2.client.provider.github.user-name-attribute=id


# =====================
# GEOPIFY CONFIG
# =====================

geoapify.api.key=0c49530a59ad49528eb01a179b78f0ed

# =====================
# GOOGLE CLOUD CONFIG
# =====================

spring.cloud.gcp.credentials.location=classpath:gcp/dietiestate25-storage.json

# =====================
# JWT CONFIG
# =====================
jwt.secret=${JWT_SECRET_KEY}